name: Fine-tune Gemma 2 9B

on:
  workflow_dispatch:
    # Pozwala ręcznie uruchomić workflow z interfejsu GitHub

jobs:
  fine-tune:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # lub jeśli nie masz requirements.txt: 
          # pip install transformers datasets accelerate

      - name: Download model from HF Hub (opcjonalnie)
        # Jeśli model jest publiczny i dostępny przez Transformers, nie musisz nic robić,
        # Transformers ściągną model automatycznie przy pierwszym użyciu.
        # W innym przypadku – np. autoryzacja:
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Start fine-tuning
        run: |
          python scripts/run_clm.py \
            --model_name_or_path ./gemma-2-9b \
            --train_file ./train_data.jsonl \
            --validation_file ./train_data.jsonl \
            --per_device_train_batch_size 1 \
            --per_device_eval_batch_size 1 \
            --num_train_epochs 1 \
            --output_dir ./gemma2-9b-finetuned \
            --do_train \
            --do_eval \
            --overwrite_output_dir \
            --use_auth_token True

      - name: List Files
        run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
